version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Always open security update PRs
    open-pull-requests-limit: 10
    # Add labels to PRs
    labels:
      - "dependencies"
      - "security"
    # Group all non-security updates into a single PR
    groups:
      all-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
    # Separate security updates
    allow:
      - dependency-type: "all"